### PR TITLE
Make sure output is visible with large values

### PR DESCRIPTION
**Pull request by skratchdot**
This seemed to help a little bit when viewing on the desktop.

### CODE REVIEW

**Comment by skratchdot** [comment]
Very cool little demo.  This is a small change to help make the float value visible.  You can compare the differences by turning on the "first 3 green bits" on these 2 pages:

http://projects.skratchdot.com/float-toy/
vs
https://evanw.github.io/float-toy/

**Comment by evanw** [comment]
Thanks! I also added min-width so the numbers don't disappear completely on smaller screens.

**Comment by skratchdot** [comment]
@evanw - That makes sense.  I was a bit worried that I might've hosed something w/ mobile, but I made my desktop browser as small as possible and it seemed okay.

Seeing your project also gave me an idea :)  I've seen a few demos that show the underlying bit structure of data, etc.  I think creating an "awesome-bits" project in the spirit of https://github.com/sindresorhus/awesome would be cool

**Comment by skratchdot** [comment]
So things like your float-toy, and other "bit" demos like calculators, etc could be included.

http://codepen.io/william-index/pen/jbwggX
http://plnkr.co/edit/hWpLZfkUKoNuNPiPJvs8?p=preview

There's a pure css ascii->binary bit flipper I found a few weeks ago, but my google-fu is failing me, and I can't find it now.

**Pull request merged**
